"""Bloom-filter style one-way fingerprint.

This module ships :class:`BloomFingerprint`, a one-way cipher that
maps a plaintext to a fixed-size bit array (a Bloom-filter style
fingerprint).  The output is identical in length to the configured
``size`` parameter and is fully bytes-like, so it integrates with the
rest of :mod:`shredder_encryptor.codec`.

The class is integrated with :mod:`shredder_encryptor.framework` and
inherits from :class:`BaseCipher`.  ``DECRYPTABLE`` is ``False`` so
the cipher refuses every decrypt call.

The fingerprint is generated by hashing the plaintext (with the
configured ``salt`` prepended) once with SHA-256 and using the
``hashes`` parameter to derive independent bit positions from the
digest.  The construction is intentionally simple so the unit tests
can model its behaviour exactly; it is **not** a secure Bloom
filter and should not be used as one.

Typical use::

    from shredder_encryptor.boom import BloomFingerprint

    cipher = BloomFingerprint(size=32, hashes=8, salt=b"v1")
    digest = cipher.encrypt(b"hello world")
    # ``digest`` is exactly 32 bytes long; ``cipher.verify`` returns
    # ``True`` for the same plaintext and ``False`` for any other.
"""

from __future__ import annotations

from hashlib import sha256
from typing import ClassVar, Final

from ..codec.b64 import encode as b64_encode
from ..codec.hexutil import to_hex
from ..framework.base import BaseCipher

__all__ = ["BloomFingerprint", "DEFAULT_SIZE", "DEFAULT_HASHES"]


#: Default fingerprint size in bytes (1 byte = 8 bits).
DEFAULT_SIZE: Final[int] = 16

#: Default number of independent hash positions derived from the
#: SHA-256 digest.  The value matches the recommended starting point
#: for small Bloom filters.
DEFAULT_HASHES: Final[int] = 4


class BloomFingerprint(BaseCipher):
    """One-way Bloom-filter style fingerprint.

    Parameters
    ----------
    size:
        Length of the fingerprint in bytes.  Must be a positive
        integer.  The default is :data:`DEFAULT_SIZE`.
    hashes:
        Number of bit positions derived from the SHA-256 digest.
        Must be a positive integer.  Two fingerprints for the same
        plaintext are guaranteed to share all ``hashes`` positions
        so :meth:`verify` can rely on an exact equality check.
    salt:
        Optional bytes prepended to the plaintext before hashing.
        Like :class:`shredder_encryptor.cipher.Sha256Hash`, a random
        salt makes pre-computed tables infeasible.
    """

    algorithm: ClassVar[str] = "bloom"
    DECRYPTABLE: ClassVar[bool] = False
    digest_size: ClassVar[int] = DEFAULT_SIZE

    def __init__(
        self,
        *,
        size: int = DEFAULT_SIZE,
        hashes: int = DEFAULT_HASHES,
        salt: bytes = b"",
    ) -> None:
        if not isinstance(size, int) or isinstance(size, bool):
            raise TypeError(f"size must be an int, got {type(size).__name__}")
        if size <= 0:
            raise ValueError("size must be a positive integer")
        if not isinstance(hashes, int) or isinstance(hashes, bool):
            raise TypeError(f"hashes must be an int, got {type(hashes).__name__}")
        if hashes <= 0:
            raise ValueError("hashes must be a positive integer")
        if not isinstance(salt, (bytes, bytearray, memoryview)):
            raise TypeError("salt must be bytes-like")
        super().__init__(size=size, hashes=hashes, salt=bytes(salt))

    def _positions(self, plaintext: bytes) -> list[int]:
        """Return ``hashes`` distinct bit positions in ``[0, size*8)``."""

        size: int = self._params["size"]
        hashes: int = self._params["hashes"]
        salt: bytes = self._params["salt"]
        digest: bytes = sha256(salt + plaintext).digest()
        bit_count: int = size * 8
        positions: list[int] = []
        cursor: int = 0
        # Walk the digest in 4-byte chunks so we can build up to
        # ``hashes`` 32-bit positions without binding the construction
        # to a specific hash size (the digest is 32 bytes, so we
        # have exactly enough for 8 chunks).
        while len(positions) < hashes:
            chunk: int = int.from_bytes(digest[cursor : cursor + 4], "big")
            cursor += 4
            if cursor > len(digest):
                # Wrap the digest with a counter so very large
                # ``hashes`` values still produce a deterministic
                # stream of positions.
                digest = sha256(digest + bytes([cursor & 0xFF])).digest()
                cursor = 0
            positions.append(chunk % bit_count)
        return positions

    def encrypt(self, plaintext: bytes) -> bytes:
        raw: bytes = self._require_bytes(plaintext, "plaintext")
        size: int = self._params["size"]
        fingerprint: bytearray = bytearray(size)
        for position in self._positions(raw):
            fingerprint[position // 8] |= 1 << (position % 8)
        return bytes(fingerprint)

    def verify(self, plaintext: bytes, digest: bytes) -> bool:
        """Return ``True`` when ``digest`` matches :meth:`encrypt`.

        Equality is structural: the two byte strings must be
        exactly identical.  The Bloom-filter semantics means
        equality is a stronger check than membership, which is
        what the project conventions expect.
        """

        clean_plain: bytes = self._require_bytes(plaintext, "plaintext")
        clean_digest: bytes = self._require_bytes(digest, "digest")
        return self.encrypt(clean_plain) == clean_digest

    def encrypt_hex(self, plaintext: bytes) -> str:
        """Return the fingerprint as a lower-case hex string."""

        return to_hex(self.encrypt(plaintext))

    def encrypt_b64(self, plaintext: bytes) -> str:
        """Return the fingerprint base64-encoded."""

        return b64_encode(self.encrypt(plaintext))
