"""One-way keyed shuffle with destroyed state.

This module ships :class:`ScrambleCipher`, an irreversible cipher
that shuffles the plaintext bytes using a keyed Fisher–Yates pass and
then *destroys* the key state.  Because the per-byte key material is
consumed during the shuffle and is not stored anywhere, the original
order of the bytes cannot be recovered from the output alone (the
output is a fixed permutation of the input but the permutation key
has been wiped).

The class is integrated with :mod:`shredder_encryptor.framework` and
inherits from :class:`BaseCipher`.  ``DECRYPTABLE`` is ``False``.

Typical use::

    from shredder_encryptor.boom import ScrambleCipher

    cipher = ScrambleCipher(b"my-key")
    digest = cipher.encrypt(b"hello world")
"""

from __future__ import annotations

from hashlib import sha256
from struct import pack
from typing import ClassVar, Final

from ..codec.b64 import encode as b64_encode
from ..codec.hexutil import to_hex
from ..framework.base import BaseCipher

__all__ = ["ScrambleCipher"]


MIN_KEY_SIZE: Final[int] = 1


class ScrambleCipher(BaseCipher):
    """One-way keyed shuffle that consumes its key state.

    The cipher performs a Fisher–Yates pass driven by a key
    stream.  The key stream is generated by hashing the configured
    key together with the current working buffer; the resulting
    bytes are consumed one per swap and never stored outside the
    working buffer.  Because the chain of intermediate states is
    gone, the inverse permutation cannot be reconstructed.

    Parameters
    ----------
    key:
        Bytes-like key material.  Must contain at least one byte.
    rounds:
        Number of Fisher–Yates passes (default 1).  Multiple rounds
        multiply the work factor for an attacker who tries to guess
        the permutation, but they also increase the running time.
    """

    algorithm: ClassVar[str] = "scramble"
    DECRYPTABLE: ClassVar[bool] = False

    def __init__(self, key: bytes, *, rounds: int = 1) -> None:
        key_bytes: bytes = bytes(key)
        if len(key_bytes) < MIN_KEY_SIZE:
            raise ValueError(f"ScrambleCipher key must be at least {MIN_KEY_SIZE} byte")
        if not isinstance(rounds, int) or isinstance(rounds, bool):
            raise TypeError(f"rounds must be an int, got {type(rounds).__name__}")
        if rounds < 1:
            raise ValueError("rounds must be a positive integer")
        super().__init__(key=key_bytes, rounds=rounds)

    def _keystream(self, length: int, *, salt: bytes) -> bytes:
        if length < 0:
            raise ValueError("length must be non-negative")
        if not length:
            return b""
        key: bytes = self._params["key"]
        pieces: list[bytes] = []
        counter: int = 0
        produced: int = 0
        while produced < length:
            digest: bytes = sha256(key + salt + pack(">Q", counter)).digest()
            pieces.append(digest)
            produced += len(digest)
            counter += 1
        return b"".join(pieces)[:length]

    def _fisher_yates(self, buffer: bytearray, salt: bytes) -> None:
        length: int = len(buffer)
        if length < 2:
            return
        key_stream: bytes = self._keystream(length - 1, salt=salt)
        for index in range(length - 1, 0, -1):
            swap_with: int = key_stream[length - 1 - index] % (index + 1)
            if swap_with != index:
                buffer[index], buffer[swap_with] = (
                    buffer[swap_with],
                    buffer[index],
                )

    def encrypt(self, plaintext: bytes) -> bytes:
        raw: bytes = self._require_bytes(plaintext, "plaintext")
        buffer: bytearray = bytearray(raw)
        rounds: int = self._params["rounds"]
        for round_index in range(rounds):
            salt: bytes = len(buffer).to_bytes(8, "big") + bytes([round_index])
            self._fisher_yates(buffer, salt)
        return bytes(buffer)

    def encrypt_hex(self, plaintext: bytes) -> str:
        """Return the shuffled cipher text as a lower-case hex string."""

        return to_hex(self.encrypt(plaintext))

    def encrypt_b64(self, plaintext: bytes) -> str:
        """Return the shuffled cipher text base64-encoded."""

        return b64_encode(self.encrypt(plaintext))
